server:
  port: 8012
spring:
  application:
    name: openfeign-provider

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  # eureka.instance.prefer-ip-address  表示将自己的IP注册到Eureka Server上，
  # 若不配置，会将当前服务提供者所在的主机名注册到 Eureka Server 上
  instance:
    prefer-ip-address: true
